service: rails-api

plugins:
  - serverless-ruby-layer

provider:
  name: aws
  runtime: ruby3.2
  region: us-east-1
  environment:
    PORT: "8080"

functions:
  api:
    handler: lambda_function.handler
    events:
      - httpApi:
          path: "/{proxy+}"
          method: ANY 